### ISSUE TITLE
Repo Improvements

### ISSUE THREAD

**Issue by amihaiemil** [oussamahamdaoui/forgJs#31]
Hi, I saw a reddit post asking for improvement suggestions in this repo. Here goes:

1. Use [Rultor](http://www.rultor.com/) for automating merge/deploy/release operations.
2. Use ``Puzzle Driven Development`` and [0pdd](http://www.0pdd.com/) for task management. 

If it sounds interesting and want more details, feel free to ask, I'll be glad to help.

Have fun!

**Comment by amihaiemil** [comment]
@oussamahamdaoui  Just note that Rultor is not a replacement for Circle CI (or Travis CI), it is an addition, something complementary. [Here]( https://www.yegor256.com/2014/07/31/travis-and-rultor.html) is a blog post about it. Also, see how I use it for merge [here](https://github.com/amihaiemil/docker-java-api/pull/189#issuecomment-441961211). :)

**Comment by oussamahamdaoui** [comment]
Thanks I was looking for a tool like that I wanted to have gitflow but I didn’t know what tool to use. I really like your ticket managing workflow I’ll try doing the same here.
I’ll ask you for help if I get stuck if you don’t mind.
🙏

**Comment by amihaiemil** [comment]
Sure, no problem :)
