### ISSUE TITLE
Type boolean?

### ISSUE THREAD

**Issue by cope** [oussamahamdaoui/forgJs#37]
This might be a stupid question, but how can I add a boolean rule in a validator?

in other words, if I have an object {a:1, b:true} I can test for a to be an integer, but how do I test for b to be a boolean?

**Comment by cope** [comment]
Ok, got it... `new Rule({type: 'int', min: 0, max: 1})`

**Comment by oussamahamdaoui** [comment]
hey, if you want to check this object here is a rule that might help 
```javascript 
const custom = new Validator({
    a: new Rule({type: 'int', min: 0, max: 1});
    b: new Rule('boolean'),
});

custom.test({a: 1, b: true}); // this will be true
custom.test({a: 1, b: 'hello'}); // this will be false
```

**Comment by oussamahamdaoui** [comment]
That’s already there, check the section
