### ISSUE TITLE
Error message as fucntions

### ISSUE THREAD

**Issue by Nevoss** [oussamahamdaoui/forgJs#43]
Hey, I did a quick scan for the repo and I like what I see, I have written a Form library and I was seeking for some package like this one to fill out the validation part (didn't find something that I like so I write some light validation class inside my library). so I thinking about using this library,

some feature that I think will be great is to set the error message as a function for example:

```js
const createMinIntRule = (num) => {
 return new Rule(
   { type: 'integer', min: num }, 
   (key, value) => `${key} must be greater then ${num}, ${value} is not enough` 
  )
}
```
and then you can create more reusability in your rules, let me know what do you think about it, I will love to make a pull request with implementation,

of course there that the option of a string as an error message will be still working.

**Comment by Nevoss** [comment]
I will +1

**Comment by oussamahamdaoui** [comment]
I was thinking about the proposition you made and I dont know what behaviour we should get when the error is in multiple keys like so:
```javascript 
const createMinMaxIntRule = (min, max) => {
 return new Rule(
   { type: 'integer', min, max }, 
   (key, value) => `${key} must be greater then ${num}, ${value} is not enough` 
  )
} // whats te expected behaviour in the case where the int doesn't resbect both max and min 
```

**Comment by oussamahamdaoui** [comment]
Let's keep the talk here if you dont mind.
I have an other idea which is going and keep this clean and wont break copmpatibility tell me what you think of this:
```javascript 
const vComplexe = new Validator({
  age: new Rule({
    type: 'int', min: 18, max: 99,
  }, 'age must be integer and between 18 and 99'),
  dateOfBirth: new Rule({ type: 'date' }, 'date must be a date'),
  name: new Rule({ type: 'string', minLength: 2 }, (key, value) => ({
    type: `${key} must be a string, ${value} is not a string`,
    minLength: `${key} must be at least 2 characters, ${value} is not`,
  })),
});
vComplexe.getErrors({
  age: 16,
  dateOfBirth: new Date(),
  name: 'a',
});
```
I still don't know what should be returned

**Comment by Nevoss** [comment]
do you want that the error will return an object of errors like this:
```JS
{
  type: 'name must be a string,',
  minLength: 'name must be at least 2 chars',
}
```

or 
```JS
[ 'name must be a string,', 'name must be at least 2 chars',]
```

and how it is going to work? if fall on the first error then the other checks are not validating?

**Comment by oussamahamdaoui** [comment]
I think we should make another function get error in rule that goes trough all the object and returns all the errors for the rule like it’s done for validator. We can make a default error message if none is provided. Do you think this approche is right?

**Comment by Nevoss** [comment]
FIrst how does the API will look like, something like this?
```JS
new Rule({
    type: 'int', min: 18, max: 99,
 }, { 
  // If the error is object it will run over the object and collect errors if needed

  type: 'type error', // you can pass error as string inside the object

  min: (key) => `${key} with min error` // you can pass errors in function inside the object

}), // but you will also need to set a default message for all the other properties that does not have message decleration (letting the user chose the default message)
```

and then we need to think how it will work with the existing code, because now it is just checking each propery and return true or false maybe some function like "testWithErrors" or somthing, that will test and will return array of errors at the end, if the array is empty thats mean that there is no errors

tell me what do you think about it? and do you have idea for the defaukt message?

**Comment by oussamahamdaoui** [comment]
That looks good I’ll try doing the first part today i don’t want to break to much code I’ll try my best if you already have an idea on how to do it I’ll be happy to see it

**Comment by Nevoss** [comment]
I will try do something later
