### ISSUE TITLE
Support for validating Nested Objects

### ISSUE THREAD

**Issue by abhaypai2611** [oussamahamdaoui/forgJs#46]
Hey there. Loved the repo! I had a question though. How do you support nested Objects. Just for an example, if we have a object like

`{ name: { first_name: 'John', last_name: 'Doe' }, address: { city: 'Mumbai', country: 'India' } }`

How do we go about validating this?

**Comment by oussamahamdaoui** [comment]
Hey, thank you for your feedback.
To validate an object is as symple as: 
```javascript 
const user = new Validator({
    name: {
        first_name: new Rule('string'),
        last_name: new Rule('string')
    },
   address: {
       city: new Rule('string'),
       country: new Rule('string')
    }
});
