### ISSUE TITLE
The equal value of rule

### ISSUE THREAD

**Issue by lxmfly123** [oussamahamdaoui/forgJs#47]
The doc says type `string` has a `equal`  check, which value should be `int`. But the code actually checks if the string value is exactly *equal* to the parameter.  
![screen shot 2018-12-16 at 11 07 02 am](https://user-images.githubusercontent.com/2769678/50049569-30757d00-0123-11e9-9250-a745dbad8457.png)

**Comment by oussamahamdaoui** [comment]
Hey thanks, my bad it’s a mistake (that’s because of copy paste). I’m fixing that

**Comment by lxmfly123** [comment]
Don't forget `email`, `password` and url`.
Also thanks to your great job on forgJs.

**Comment by oussamahamdaoui** [comment]
Your welcome, it’s not only me there are some people now and you are part of them now. Thanks by the way didn’t see that 😬. I really should stop copy paste
