### ISSUE TITLE
allowed fields

### ISSUE THREAD

**Issue by muturgan** [oussamahamdaoui/forgJs#49]
this package is awesome. thnk you!

suggestion for the functionality extands. 

it will be very usefull to check required and allowed keys in anobject

**Comment by oussamahamdaoui** [comment]
Can you explain please 😕
All fealds are required by default, if you need optional feeld you have to use optional in your rules
Thanks for your help

**Comment by muturgan** [comment]
oh, I thougth I made my answer...
I will try again

**Comment by oussamahamdaoui** [comment]
I got it didn't see that you have changed the title its clear now
Do you have an idea on how that is going to work?

**Comment by oussamahamdaoui** [comment]
I undestood that partm but i dont  a nice sintax for that? Do you have any suggestions

**Comment by muturgan** [comment]
well may be something like:
```
v.test({
    firstName: 'John',
    lastName: 'Smith',
}, true);
```

**Comment by oussamahamdaoui** [comment]
that looks good, thats a good idea, ill try to implement this.

**Comment by oussamahamdaoui** [comment]
Hey, sorry for the wait i ended up making all fildes present in the validator requred so if there is a field  thats not in the rulle the return will be false.
I also updated the npm version
Hope this helps
