### ISSUE TITLE
Validator.getErrors()

### ISSUE THREAD

**Issue by theSymbeint** [oussamahamdaoui/forgJs#50]
Validator.getErrors() methods returns a function definition for me and not a string.

**Comment by Nevoss** [comment]
Can you please give us more details? how does your code look like?

**Comment by theSymbeint** [comment]
Here's a sample of the way I'm trying it:

```javascript
const {Validator, Rule} = require('@cesium133/forgjs')


const rule = new Rule({type: 'int'}, (key, value) => {
    return '${key} must be an integer'
})

const  intVal = new Validator({
intField:rule
})

let n = "string"

let msg = intVal.getErrors({
intField: n 
})

console.log(msg)
```

**Comment by oussamahamdaoui** [comment]
My bad sorry, forgot to do the release of the update 😬.
Updating ... 
it will be updated when I close the issue.
Ps: don’t forget to update your local version with npm install

**Comment by theSymbeint** [comment]
No Problem.😅I thought it was me.

**Comment by oussamahamdaoui** [comment]
Done please tell me if its working now
