### ISSUE TITLE
Duplicate error messages when check for multiple types.

### ISSUE THREAD

**Issue by XX-NF-XX** [oussamahamdaoui/forgJs#65]
Example:
```javascript
const { Validator, Rule } = require('@cesium133/forgjs');

const validator = new Validator({
  value: new Rule(
    {
      type: 'int|float',
      min: 1
    },
    'Error message'
  ),
});

validator.getErrors({
  value: 0,
});  // [ 'Error message', 'Error message' ]
```

One rule, one custom error message, but multiple errors in array.

I was trying to fix it and send a PR, but it seems like you have unfinished or undocumented work there.

**Comment by oussamahamdaoui** [comment]
Hello, sorry didn't have much time these days, ill look up and try to fix this

**Comment by WalterCJ** [comment]
Hey guys, I didn't quit tested but... can't you just do something like this before adding to errors list?

```javascript
if(anotherOperand && this.errorCollector.errors.length > 0){
    return false
}
```
