### ISSUE TITLE
Optional property to support "empty" values

### ISSUE THREAD

**Issue by balazsorban44** [oussamahamdaoui/forgJs#80]
Hi! I have the following example:
```js
// value is one of "", "ABCD1234"
const discountCode = new Rule({
  type: 'string',
  match: /^[A-Z0-9]$/,
  optional: true,
  minLength: 8,
  maxLength: 8
}).test(value)
```

Setting the `optional` property does not work here right now, because it requires the value to be either undefined or something that matches the Rule. I was curious if there is a possibility to state somewhere that `""` should be also acceptable? I could do either `value = "" || ...` or
```js
Rule({
  type: 'string',
  match: /^$|^[A-Z0-9]{8}$/
})
```
, just curious if there is a cleaner way?

**Comment by oussamahamdaoui** [comment]
Hey, sorry I have been a little bit bussy these days (some free time is coming soon 🎉) thank you for the question. The main goal of this project is to be easy to add your own Rules and that was what the lib was meant for here is an example of how I would have made your rule

```javascript

 Rule.addCustom('discountCode', {
    type: val => /^$|^[A-Z0-9]{8}$/.test(val),
    startsWith: (val,start)=> val.startsWith(start),
   // here you can add more options
  });

// then do this later

const discountCode = new Rule({type:'discountCode'});
const discoutCode2019 = new Rule({type:'discountCode', startsWith:'2019'});


```
