### ISSUE TITLE
Validating an empty string with notEmpty=false returns false

### ISSUE THREAD

**Issue by balazsorban44** [oussamahamdaoui/forgJs#81]
Take this example:

```js
new Rule({
  type: "string",
  notEmpty: false
})
.test("") // should return true
```

**Comment by oussamahamdaoui** [comment]
Thanks, I think that this rule should be renamed, i didn't think that much when i named it and now i'm having hard time understanding. I'll fix this one and add a new rule called `isEmpty` to avoid double negatives

**Comment by oussamahamdaoui** [comment]
Hey @morpheus7CS, can you reopen this pull request please. what do you guys think should we keep both notEmpty and isEmpty or can we make a small braking change with completely removing the old notEmpty rule ? 
👍for completely replacing the rule
👎for keeping both notEmpty and isEmpty

**Comment by balazsorban44** [comment]
Could keep both, and release a major version bump where it is either removed, or it is kept still, but an error thrown in development mode that says in the NEXT major version it will be removed. this gives plenty of time to everyone to adapt.

**Comment by morpheus7CS** [comment]
@oussamahamdaoui Hey, sorry for the late reply. 

Yes, I will gladly reopen the pull request. I'll wait a few days to see how your poll shakes out ;)

Kind regards,
g

**Comment by morpheus7CS** [comment]
Hey @oussamahamdaoui,

so, I added the isEmpty and am about ready to push the PR. However, there are some issues. I want to run these by you so that we can come to a final decision and then I'll gladly push the PR your way.

First, I defined the isEmpty in the `src/testFunctions/primitives.js`as:
````js
const STRING = {
  minLength: (val, min) => val.length - min >= 0,
  maxLength: (val, max) => val.length - max <= 0,
  equal: (val, equal) => val === equal,
  match: (val, regex) => regex.test(val),
  notEmpty: val => val !== '',
  isEmpty: val => val === '',
  type: isString,
};
````
and in the `src/testFunctions/types/array.js`:
````js
const array = {
  of: (arr, rule) => {
    let ret = true;
    arr.forEach((el) => {
      if (rule.test(el) === false) {
        ret = false;
      }
    });
    return ret;
  },
  notEmpty: val => val.length !== 0,
  isEmpty:  val => val.length === 0,
  length: (val, len) => val.length === len,
  type: isArray,
};
````
Next, in order to keep things simple, I added the isEmpty on all the tests, that already tested the notEmpty validation rule like so:
````js
test('some test', () => {
  const arrayRule = new Rule({
    type: 'array',
    notEmpty: true,
    isEmpty: false,
  }, null);
  expect(arrayRule.test([])).toBe(false);
});
````
The idea is that if `notEmpty: true`validates as true, then it should also validate as true if we use the inverse.

However, I get 3 failing tests when doing this:
````bash
Summary of all failing tests
 FAIL  test/Rule/string.test.js
  ● type string returns true when string not empty

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      50 |     isEmpty: false,
      51 |   }, null);
    > 52 |   expect(strRule.test('the quick brown fox')).toBe(true);
         |                                               ^
      53 | });
      54 |
      55 | test('type string returns false when string empty', () => {

      at Object.toBe (test/Rule/string.test.js:52:47)

  ● type string returns true when two strings are equal

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      69 |     equal: 'hello',
      70 |   }, null);
    > 71 |   expect(strRule.test('hello')).toBe(true);
         |                                 ^
      72 | });
      73 |
      74 | test('type string returns true when string minLength', () => {

      at Object.toBe (test/Rule/string.test.js:71:33)

  ● type string returns true when string minLength

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      79 |     minLength: 2,
      80 |   }, null);
    > 81 |   expect(strRule.test('hello')).toBe(true);
         |                                 ^
      82 | });
      83 |

      at Object.toBe (test/Rule/string.test.js:81:33)


Test Suites: 1 failed, 20 passed, 21 total
Tests:       3 failed, 129 passed, 132 total
Snapshots:   0 total
Time:        1.915s, estimated 2s
Ran all test suites.
````

So, it either I'm doing the type definition wrong, or we have identified additional issues that have to be addressed.

Let me know & kind regards,
g

**Comment by oussamahamdaoui** [comment]
Hey @morpheus7CS , I know why this is not working as expected: let me explain how the Rule object works hopefully this will help people write and add new rules more frequently, lets say that you create a rule like this:

```javascript
 const arrayRule = new Rule({
    type: 'array',
    notEmpty: true,
    isEmpty: false,
  }, null);
 ```
when you call `arrayRule.test([])`  what happens is:
 1 - the type check is done first it gets the function that validates the type of the object provided to `test` in this example it is going to be `isArray([])` which returns `true`
2 - then it is going to call all the other test functions if one of them returns false then te final result is false in this example it is going to call `notEmpty([], true, null)` (the first parameter is the value that is tested in this example `[]` the second is the value in the rule object in this case `true`, the last parameter is the hole object when the Rule is in a Validator )in this implementation it will return `[].length !== 0 ` witch is `false` so it returns `false` it doesn't go to the next call. What you need to add is `notEmpty: (val, shouldItBeEmpty) => (val.length === 0) === shouldItBeEmpty` this way when called `notEmpty([], true, null)` it's going to do `([].length === 0 ) === true` witch is `true` and when `notEmpty` is set to false this is going to be `notEmpty([], false, null)` witch is `([].length === 0) === false`
3 - after notEmpty is validated its going to call `isEmpty([], true, null) witch should be something like `isEmpty: (val, shouldItBeEmpty) => (val.length !== 0) === shouldItBeEmpty` this way you get `([].length !== 0) === false` which is `true`.

Long story short I think the correct way should be something like:

```javascript
const STRING = {
  minLength: (val, min) => val.length - min >= 0,
  maxLength: (val, max) => val.length - max <= 0,
  equal: (val, equal) => val === equal,
  match: (val, regex) => regex.test(val),
  notEmpty: (val, itShouldNotBeEmpty) => (val !== '') === itShouldNotBeEmpty,
  isEmpty: (val, itShouldBeEmpty) => (val === '') === itShouldBeEmpty,
  type: isString,
};
```


```javascript
const array = {
  of: (arr, rule) => {
    let ret = true;
    arr.forEach((el) => {
      if (rule.test(el) === false) {
        ret = false;
      }
    });
    return ret;
  },
 notEmpty: (val, itShouldNotBeEmpty) => (val.length !== 0) === itShouldNotBeEmpty,
  isEmpty: (val, itShouldBeEmpty) => (val. length === 0) === itShouldBeEmpty,
  length: (val, len) => val.length === len,
  type: isArray,
};

```

Thank you for your help, if you have any questions feel free to ask. I hope that my explication was clear 😅

PS: if any of you guys @balazsorban44 @morpheus7CS want to be contributors to the project I'll be happy to give you the rights 😉, I was thinking of cleaning the code, removing a lot of useless files and adding more features.

**Comment by morpheus7CS** [comment]
Cool, thanks for explaining!

I plan on helping out whenever possible, but I find it helpful when I also have another person look at the code before it is merged in ;)

Kind regards,
g
